apiVersion: v1
kind: Service
metadata:
  name: ingress
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 50000-tcp
    port: 50000
    protocol: TCP
    targetPort: 50000
  loadBalancerIP: 192.168.1.5
  type: LoadBalancer
  selector:
    deploymentconfig: jenkins
