apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: pipeline
    name: pipeline
  name: pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:  "node() {\nstage 'build'\nopenshiftBuild(namespace: 'development', buildConfig: 'apachewebserver', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(namespace: 'development', deploymentConfig: 'apachewebserver')\nopenshiftScale(namespace: 'development', deploymentConfig: 'apachewebserver',replicaCount: '2')\n}"
      type: JenkinsPipeline
  triggers:
   - github:
       secret: S51F5dU_gnt19RQ1Z6rO
     type: GitHub
   - generic:
       secret: NpyZ9EoEs7SBDi7jMVqJ
     type: Generic
status:
  lastVersion: 0
